
configMapGenerator:
- files:
  - envs/msg
  name: appconfig
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: quay.io/apoczeka/sample-app:latest
  newName: quay.io/apoczeka/sample-app
  newTag: eaecfa4d0af19bd5a8fe8f94cf8e753ad435d22e
