apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-sample-app
  labels:
    app: sample-app
    createdBy: "apoczekalewicz-openshift-gitops"
spec:
  params:
    - default: 'http://myallure.allure.svc.cluster.local:5050'
      name: allure_host
      type: string
    - default: 'http://sample-app.sample-app-dev.svc.cluster.local'
      name: app_url
      type: string
    - default: 'https://github.com/apoczekalewicz/sample-app.git'
      name: APP_SOURCE_GIT
      type: string
    - default: master
      name: APP_SOURCE_REVISION
      type: string
    - default: latest
      name: APP_IMAGE_TAG
      type: string
    - default: quay.io/apoczeka/sample-app
      name: APP_IMAGE
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.APP_SOURCE_GIT)
        - name: revision
          value: $(params.APP_SOURCE_REVISION)
        - name: submodules
          value: 'true'
        - name: depth
          value: '01'
        - name: sslVerify
          value: 'false'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:da1aedf0b17f2b9dd2a46edc93ff1c0582989414b902a28cd79bad8a035c9ea4
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: skopeo-copy
      params:
        - name: srcImageURL
          value: >-
            docker://image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(context.pipeline.name):$(params.APP_IMAGE_TAG)
        - name: destImageURL
          value: 'docker://$(params.APP_IMAGE):$(params.APP_IMAGE_TAG)'
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'true'
      runAfter:
        - build-image
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: images-url
    - name: build-image
      params:
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(context.pipeline.name):$(params.APP_IMAGE_TAG)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:99cae35f40c7ec050fed3765b2b27e0b8bbea2aa2da7c16408e2ca13c60ff8ee
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Containerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: >-
            --squash
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
    - name: dast-zap-proxy
      params:
        - name: APPLICATION_NAME
          value: zap-scan
        - name: APP_URL
          value: $(params.app_url)
        - name: ALLURE_HOST
          value: $(params.allure_host)
        - name: ALLURE_SECRET
          value: allure-auth
        - name: WORK_DIRECTORY
          value: /zap-proxy
      taskRef:
        kind: Task
        name: zap-proxy
      runAfter:
        - git-clone
      workspaces:
        - name: output
          workspace: workspace
  workspaces:
    - name: workspace
    - name: images-url

