apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-sample-app
  labels:
    app: sample-app
    createdBy: "apoczekalewicz-openshift-gitops"
spec:
  params:
    - default: 'https://github.com/apoczekalewicz/sample-app.git'
      name: APP_SOURCE_GIT
      type: string
    - default: master
      name: APP_SOURCE_REVISION
      type: string

    - default: latest
      name: APP_IMAGE_TAG
      type: string
    - default: quay.io/apoczeka/sample-app
      name: APP_IMAGE
      type: string

    - default: 'https://github.com/apoczekalewicz/openshift-gitops.git'
      name: APP_MANIFESTS_GIT
      type: string
    - default: sample-app
      name: APP_NAME
      type: string


  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.APP_SOURCE_GIT)
        - name: revision
          value: $(params.APP_SOURCE_REVISION)
        - name: submodules
          value: 'true'
        - name: depth
          value: '01'
        - name: sslVerify
          value: 'false'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:da1aedf0b17f2b9dd2a46edc93ff1c0582989414b902a28cd79bad8a035c9ea4
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build-image
      params:
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(context.pipeline.name):$(params.APP_IMAGE_TAG)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:99cae35f40c7ec050fed3765b2b27e0b8bbea2aa2da7c16408e2ca13c60ff8ee
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Containerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: >-
            --squash
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
    - name: skopeo-copy
      params:
        - name: srcImageURL
          value: >-
            docker://image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(context.pipeline.name):$(params.APP_IMAGE_TAG)
        - name: destImageURL
          value: 'docker://$(params.APP_IMAGE):$(params.APP_IMAGE_TAG)'
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'true'
      runAfter:
        - build-image
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: images-url
    - name: git-update-deployment
      params:
        - name: GIT_REPOSITORY
          value: $(params.APP_MANIFESTS_GIT)
        - name: CURRENT_IMAGE
          value: '$(params.APP_IMAGE):latest'
        - name: NEW_IMAGE
          value: $(params.APP_IMAGE)
        - name: KUSTOMIZATION_PATH
          value: apps/$(params.APP_NAME)/dev
        - name: GIT_REVISION
          value: master
        - name: NEW_TAG
          value: $(params.APP_IMAGE_TAG)
      runAfter:
        - skopeo-copy
      taskRef:
        kind: Task
        name: git-update-deployment
      workspaces:
        - name: workspace
          workspace: workspace
        - name: basic-auth
          workspace: git-basic-auth
    - name: gitops-sync
      params:
        - name: application-name
          value: $(params.APP_NAME)-dev
        - name: revision
          value: HEAD
        - name: flags
          value: '--insecure'
        - name: argocd-version
          value: v2.6.7
      runAfter:
        - git-update-deployment
      taskRef:
        kind: ClusterTask
        name: argocd-task-sync-and-wait

  workspaces:
    - name: workspace
    - name: images-url
    - name: git-basic-auth
