apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sonar-properties
spec:
  encryptedData:
    sonar-project.properties: AgAbY4QOzi8yXvXpjZFBn5bcHl/9KyguL+v7t1pPxOn3uZGMXEOxJD960uE4nwSAQ+PNQBKnzaqzuDn34cx6saKq5NShfQ7DfDEgtiNMynl4FOjbPV1LnxoYAVL1RXP56e5g35GWYbxzxx0qe21CR5zEb87HzVjgVq/fNviX2W94ETersBVH7z08roMiOSyNbo3hCwUCH7KjkH4X5a7s06uN2FSg9MVuZ1SsN+lUc/gDEJdC1TYx7LbMZ9gDGOP8qbKJ6NQS2ppEFU0z+qrXUOh6iSI0GTFWmgs9o/qygXhvNCDCacG0Q8/eRfGopBWEo+FOG/uSHz0aq77wy62RiO9Yim0l5vZ5MMNRo6CFpsRHhthAeD3GtOgbRfMiBBzmSsT4h+7SbkQGZNILMqvMvi1htEVgDL8mNq8axI2QCa1WVfisa+ewjXgKJn3aDSHxhdyMJ4WYp4xbjTxGG2U4hjuY4EZh9LLslbwyFpfxhXceRnH9hwMoeuC45+UIPcjGqvVfobBiUalQ7EuR6423MAkM80okysYMbpTHK1RZuMBTHk7zphiyG1SLWD3aDQp/5AFft32WXWdlKcJqOVoKs9qerp4gtlQk8oMVeR4+jkX5g/W8/b3NkASgsIflbfHg+Fwj/GF7rPNyXoci+jlGI2cgGriH5GQTEDxT0FRE2GmxaRV80PJMHaf3fjCDIEe4EY0YUkAGm0BYpW0iH86xpS1CMUJQ13zssA8fEA+z3gnInA9E9NuRclZBwNo1bH2Q2n7KDr+f7hYJrEo03osbOLHPtrdQgVfi0GjSqQrjUvzU77di0ZvFef9I4Il2jHHmN8DjdLwFmoldOX/2uUwFfxPtp+ty6BI1iZy+mOq9Dj+w9IYZxmkgsj74eSMe0Wk1COCaMBA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sonar-properties

